// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0X1KsGmlr8XXmwE1HCYDf0eGzn8ODoPM',
    appId: '1:175125533624:web:940f6776739cbad018f54d',
    messagingSenderId: '175125533624',
    projectId: 'innerexec-bd12d',
    authDomain: 'innerexec-bd12d.firebaseapp.com',
    storageBucket: 'innerexec-bd12d.firebasestorage.app',
    measurementId: 'G-9R710ZDZZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzv2IMAz-BfwFGoz9gUJi3BJc2WJtMK_o',
    appId: '1:175125533624:android:3c0a876ea96795a918f54d',
    messagingSenderId: '175125533624',
    projectId: 'innerexec-bd12d',
    storageBucket: 'innerexec-bd12d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc8S0qQgr2YQhH_ebusHQUtCFMmLZQxRM',
    appId: '1:175125533624:ios:b6d3fa3b0c361d7518f54d',
    messagingSenderId: '175125533624',
    projectId: 'innerexec-bd12d',
    storageBucket: 'innerexec-bd12d.firebasestorage.app',
    iosBundleId: 'com.example.innerexec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc8S0qQgr2YQhH_ebusHQUtCFMmLZQxRM',
    appId: '1:175125533624:ios:b6d3fa3b0c361d7518f54d',
    messagingSenderId: '175125533624',
    projectId: 'innerexec-bd12d',
    storageBucket: 'innerexec-bd12d.firebasestorage.app',
    iosBundleId: 'com.example.innerexec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0X1KsGmlr8XXmwE1HCYDf0eGzn8ODoPM',
    appId: '1:175125533624:web:45bedfba37410e5318f54d',
    messagingSenderId: '175125533624',
    projectId: 'innerexec-bd12d',
    authDomain: 'innerexec-bd12d.firebaseapp.com',
    storageBucket: 'innerexec-bd12d.firebasestorage.app',
    measurementId: 'G-78RCD9EK28',
  );
}
